//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SRR.DataAccessLayer.Model;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SRRApplications> SRRApplications { get; set; }
        public DbSet<SRRApplicationUsingServices_Switch> SRRApplicationUsingServices_Switch { get; set; }
        public DbSet<SRREntityHistoryTable> SRREntityHistoryTable { get; set; }
        public DbSet<SRREntityTagKeywords> SRREntityTagKeywords { get; set; }
        public DbSet<SRRServiceMessages> SRRServiceMessages { get; set; }
        public DbSet<SRRServiceOperations> SRRServiceOperations { get; set; }
        public DbSet<SRRServices> SRRServices { get; set; }
        public DbSet<SRRUsers> SRRUsers { get; set; }
    }
}
