CREATE TABLE [dbo].[SRREntityTypeSet] (
    [PK_ID] INT            IDENTITY (1, 1) NOT NULL,
    [Name]  NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_SRREntityTypeSet] PRIMARY KEY CLUSTERED ([PK_ID] ASC)
);

