//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Keyword_Switch
    {
        public int FK_ApplicationPK_ID { get; set; }
        public int FK_KeywordPK_ID { get; set; }
        public int PK_ID { get; set; }
    
        public virtual SRRApplications SRRApplications { get; set; }
        public virtual SRREntityTagKeywords SRREntityTagKeywords { get; set; }
    }
}
