//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOperations
    {
        public ServiceOperations()
        {
            this.SRREntityTagKeywords = new HashSet<SRREntityTagKeywords>();
            this.ServiceOperations1 = new HashSet<ServiceOperations>();
            this.ServiceOperations2 = new HashSet<ServiceOperations>();
        }
    
        public int PK_ID { get; set; }
        public string Name { get; set; }
        public string Namespace { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string ModificationDate { get; set; }
        public string ModificationReason { get; set; }
        public string ModificationUser { get; set; }
    
        public virtual ICollection<SRREntityTagKeywords> SRREntityTagKeywords { get; set; }
        public virtual ICollection<ServiceOperations> ServiceOperations1 { get; set; }
        public virtual ICollection<ServiceOperations> ServiceOperations2 { get; set; }
    }
}
