//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRRApplications
    {
        public SRRApplications()
        {
            this.SRRApplicationUsingServices_Switch = new HashSet<SRRApplicationUsingServices_Switch>();
            this.Tags = new HashSet<SRREntityTagKeywords>();
        }
    
        public int PK_ID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public int FK_Developer { get; set; }
        public string AttachedObjects { get; set; }
        public int FK_Owner { get; set; }
    
        public virtual ICollection<SRRApplicationUsingServices_Switch> SRRApplicationUsingServices_Switch { get; set; }
        public virtual SRRUsers Developer { get; set; }
        public virtual SRRUsers Owner { get; set; }
        public virtual ICollection<SRREntityTagKeywords> Tags { get; set; }
    }
}
