//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRRApplicationUsingServices_Switch
    {
        public int FK_ApplicationPK_ID { get; set; }
        public int FK_ServicePK_ID { get; set; }
        public string RequestTransformation { get; set; }
        public string ResponseTransformation { get; set; }
        public string FaultTransformation { get; set; }
    
        public virtual SRRApplications SRRApplications { get; set; }
        public virtual SRRServices SRRServices { get; set; }
    }
}
