//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRRApplications
    {
        public SRRApplications()
        {
            this.Application_Keyword_Switch = new HashSet<Application_Keyword_Switch>();
            this.SRRApplicationUsingServices = new HashSet<SRRApplicationUsingServices>();
        }
    
        public int PK_ID { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public string Description { get; set; }
        public int FK_Developer { get; set; }
        public string AttachedObjects { get; set; }
        public string Keywords { get; set; }
    
        public virtual ICollection<Application_Keyword_Switch> Application_Keyword_Switch { get; set; }
        public virtual ICollection<SRRApplicationUsingServices> SRRApplicationUsingServices { get; set; }
        public virtual SRRUsers SRRUsers { get; set; }
    }
}
