//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRREntityTagKeywords
    {
        public SRREntityTagKeywords()
        {
            this.Application_Keyword_Switch = new HashSet<Application_Keyword_Switch>();
            this.SRRServices = new HashSet<SRRServices>();
            this.SRRServiceMessages = new HashSet<SRRServiceMessages>();
            this.ServiceOperations = new HashSet<ServiceOperations>();
        }
    
        public int PK_ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application_Keyword_Switch> Application_Keyword_Switch { get; set; }
        public virtual ICollection<SRRServices> SRRServices { get; set; }
        public virtual ICollection<SRRServiceMessages> SRRServiceMessages { get; set; }
        public virtual ICollection<ServiceOperations> ServiceOperations { get; set; }
    }
}
