//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRREntityHistoryTable
    {
        public SRREntityHistoryTable()
        {
            this.SRRUsers1 = new HashSet<SRRUsers>();
        }
    
        public int PK_ID { get; set; }
        public string ModDate { get; set; }
        public string ModReason { get; set; }
        public int FK_ModUser { get; set; }
    
        public virtual SRRUsers SRRUsers { get; set; }
        public virtual ICollection<SRRUsers> SRRUsers1 { get; set; }
    }
}
