//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRR.DataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRRServiceMessages
    {
        public SRRServiceMessages()
        {
            this.Tags = new HashSet<SRREntityTagKeywords>();
        }
    
        public int PK_ID { get; set; }
        public string Name { get; set; }
        public string Namespace { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<SRREntityTagKeywords> Tags { get; set; }
    }
}
